travis:
  secure:
    BINSTAR_TOKEN: ccbj/Ad+jlblnYZIpfpgHVbopnYJZAzxJh35SjTX3GJghs0kticCZEOz05tlIFmLCQSx0wSNg0XXgAJaRSwaK8+rCqTC8QXsLXRXCqGXE7GlaXg/TGBRaqtylosucsv+YJlooT3Q2eqtSXwupQ1OmEm7UlI2N79xNlVRIfYqstV5ndxcodonQgdn7+WlTSOq8QvsyeYpLIaPqgq7etDfiZIPXqdSX6H1/XVrNgAcN/oTxtc7M2loTFEVmiQEGl42GTkPH7lVwy5kfbq5X9RD3x2kUg1uqsvuW/IdqKZvY1SOrO8Jlh++JrJi+cmtiJ/mrpTw4PefWuLNuH5Vemfl5pGjI6M+3fEQEqYDj8jiuMzrqm+65UrppCfSfOcsb4hgSq/TSWQeUIkkHn+NmfVzQWuAS67Gq4fPLNzGtOorkCxJExBrtMVjhJFNWoFNj3KE4eS+QNu8H0EsAtwjWOC6OlX7+Aug0ep2QS3nia+Xw9b0QZrU8r/zBKZO31/2VzmgnzdL6AdhHi8179Xtr2bGVCNPou7d6rrwX2FA2T8pBZPiWl0ARDlKPX++TPIKI3FroEHJqPxJfPZKnXz5kh7u7r7EKkv1zkueUuVGa8HXGmtnnV7zH6K06/0XyvaAhCmdRWEXyYAzCpfT66QZV35QGU5RtuBs4YA5e34PoCBUpR0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
