travis:
  secure:
    BINSTAR_TOKEN: KIwjQAhVXvkjs0S2HLlPE1f5px2A/0HNIuhDgI7JSD7k4eKSmT10W8OmO1A7tcBMyhJ7J6UaYAUa8cGhgDdKE7fRN9oV8RRk6H3MnpIoa6vtzGIJtV64Rcbkg/TuTIy4LUx2MbcjGIEbVOZtUOpNmWAdeRrP8BjdyLI/6luo7q+K1Snid7g+x+x7UY4e9cb3AevM654PbNelfCMm/bqgsHEdPoYnvpoKwJzQcqPNGREOpU4G4JufccwQWDdxsVImAwFXQ1nlC9vQ0tgwwV3nxWHSPLbtDZzl4Z7pfqBHOGPRXHbSgIcAe8jHV1afMusfpoXRht0HgJXQutt6UohX3Le2DE/Fct7BiYco046v+/xQQ1TmEwuam5V1UdMcWNFU574e/dyx/OG2bEClqdsvPQKq2bDtmakNcpmpvXHL1EDpvr/qCkFPge1WrJtAD8I6sAzcdj5YPXZWA6VebKS3SM+wfoHweUQcC5ET2begf0kFfw3DtifdKNMRp6KHWYEpf4LQXtHd3bqViuczEKvu5k9XchZLfcTN0j0Jp2hrKGPGEAil88e76MPKv+Zd3/MvgB0Tq145C6xVcCS7jl3dQz/ju+Ea26Fhk2+aW3ZgeRIGWMONFm7vaoslYJgSYIb9uNkEuaORspl0MfteP243b5M4CokXQ2ylx5lz2rCcmqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
